### ISSUE TITLE
LISTAGG limit error on Redshift in intercom__contact_enhanced

### ISSUE THREAD

**Issue by ant0inemtr** [fivetran/dbt_intercom#4]
Hi!

I've already opened [a quite similar ticket for dbt_jira](https://github.com/fivetran/dbt_jira/issues/8). As I'm using Redshift, I'm encountering this error while running intercom__contact_enhanced model:

`  Result size exceeds LISTAGG limit
  DETAIL:  
    -----------------------------------------------
    error:  Result size exceeds LISTAGG limit
    code:      8001
    context:   LISTAGG limit: 65535
    query:     14150509
    location:  0.cpp:839
    process:   query1_411_14150509 [pid=19351]
    -----------------------------------------------
  compiled SQL at target/run/intercom/models/intercom__contact_enhanced.sql`

As stated in the Jira issue, fivetran_utils.string_agg is responsible for this, because with Redshift, through LISTAGG, 65535 bytes is the longest data type that Redshift is capable of storing.

Contrary to the Jira repo, there are here some variables that can disable the different LISTAGG in the repo to be run (which is imo the best thing to do to make sure LISTAGG cannot trigger this kind of error):
`  using_contact_company: False
    using_company_tags: False
    using_contact_tags: False
    using_conversation_tags: False`

Assigning False to the last 3 variables is fine. However, if using_contact_company = False, intercom__company_enhanced and intercom__company_metrics models will be disabled, so I won't have any final models regarding companies, Therefore, I don't really understand the use of `{{ config(enabled=var('using_contact_company', True)) }}` condition at the beginning of both models. In some other models such as intercom__contact_enhanced, instead of this,` {% if var('using_contact_tags', True) %} `is used, which enables you to get a model that can be run, even though some metrics are disabled. 

I hope i'm clear enough.
Thank you in advance!

**Comment by fivetran-kristin** [comment]
Hey @ant0inemtr - There are two places in the `intercom__contact_enhanced` table where we make use of LISTAGGs.  It's likely that the error is a result of aggregating all contact tags together rather than aggregating all company names associated with a single contact.

Can you test this theory by running the package with **only** the using_contact_tags variable disabled, and let me know how that goes?

```
vars:
  using_contact_tags: False
```

If you still run into an error, I'll need to update how the `using_contact_company` variable works. It currently disables a few things, and we'll need to be more specific so users have more flexibility. 

Keep me posted, thanks!!

**Comment by ant0inemtr** [comment]
Hi Kristin!

You are right, it seems to be working!
I'll keep you posted if I have this kind of issues in the future, but for this precise situation, your suggestion is correct!

Thanks again,
Antoine
